### ISSUE TITLE
ERROR: No hash found for gcc-6.4.0.tar.xz  

### ISSUE THREAD

**Issue by 652436962** [johschmitz/buildroot-quickpi#1]
ERROR: No hash found for gcc-6.4.0.tar.xz  
make: *** [package/pkg-generic.mk:148：/home/freeor/Desktop/quickpi/buildroot-quickpi-master/output/build/host-gcc-initial-6.4.0/.stamp_downloaded] 错误 1

**Comment by johschmitz** [comment]
My work was based on an older version of buildroot. I believe you can use it as a basis but need to put in some work updating to the latest version, basically just look at the config files and check out what I did in my commits. Currently I don't have a rpi available so I am not going to update this repo in the near future. The device running the resulting image however is still working as a webradio for my mother :-)
